# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b24edb7aab34b933a4d002a4321e5fb40ed8b8b76c18cae8bed2d306aa24797c769f770d48ff63d0c78aa9c18ca8ac96a595ce9270653c7ba4a15e09d73bd382
  echo_key: 75JU1NHPEPMGDPCLS
  echo_secret: xHMZcTbERKm7Pcp4zJlF8A

test:
  secret_key_base: 6b47d6c763e13c41d260e434bad5c0c10f3dbbde478428391dfc62c15657434e35ae4d858916ac2eb0a419a34bc9174ab5ab7907a40f463c037d2ca31f4398fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
